spring.application.name=Ecommerce-Project
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test


project.image = images/

#spring.jpa.show-sql =  true
#spring.jpa.properties.hibernate.format-sql = true
#spring.jpa.hibernate.ddl-auto = update


spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookie=springBootEcom

#Mysql Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=Sipu@6371353644
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Postgressql Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
#spring.datasource.username=postgres
#spring.datasource.password=Sipu@6371353644
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.example.EcommerceProject=DEBUG

logging.level.root=INFO
logging.level.com.EcommerceProject=DEBUG


